### ISSUE TITLE
WASM Target

### ISSUE THREAD

**Issue by gbb-jf** [Chaintech-Network/CMPToast#4]
Is there a chance to build this against wasm? I'm currently using `cmptoast` for a project with Android/iOS, but also wanted to build a wasm target for my app, without creating platform specific code for toasts.

**Comment by mayur-ctn** [comment]
@gbb-jf Please check version 1.0.4

**Comment by gbb-jf** [comment]
This seems to provide the wasm target. I need to resolve a few dependencies which don't have a wasm implementation to build my project correctly, but `cmptoast` doesn't seem to be a problem right now. 
Thank you!

**Comment by ctn-mobile-innovation** [comment]
@gbb-jf we are closing this issue for now
